apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 3036
      nodePort: 30036
      name: http
  selector:
    name: nginx
